# 数据操作

## 基础

- 张量(tensor)：n维数组，一个轴的tensor -> vector，两个轴的tensor -> matrix

In [4]:
import torch
import numpy

In [5]:
# arange(start,end,step,...)
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [7]:
# numbers of element
x.numel()

12

In [8]:
# reshape tensor
X=x.reshape(3,4)
# Automatically calculate the size of dimension
Y=x.reshape(-1,4)
X,Y

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [9]:
# all zero tensor
A=torch.zeros((2,3,4))
# all one tensor
B=torch.ones((2,3,4))
A,B

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

In [10]:
# 均值为0，标准差为1的标准高斯分布
torch.randn(3,4)

tensor([[-0.4675,  1.1899, -0.8467,  1.7056],
        [ 1.4157, -0.5605,  0.2085, -0.9381],
        [ 0.2101,  0.9438,  0.8242,  0.2606]])

In [11]:
torch.tensor([[2,1],[3,1],[4,3]])

tensor([[2, 1],
        [3, 1],
        [4, 3]])

## 运算符

In [12]:
# 加 减 乘 除
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y # ** 求幂操作：按位求幂

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [13]:
torch.exp(x) # e的幂

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [14]:
# 连接 concatenate
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
# 0: y-coordinate  1: x-coordinate
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
# 按位比较
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [16]:
# 所有元素求和，产生一个单元素tensor
X.sum()

tensor(66.)

## 广播机制 broadcasting mechanism

通过复制实现扩展数组，对生成的数组执行按位操作

In [17]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [18]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

即$a+b=
\begin{bmatrix}
0&0\\
1&1\\
2&2\\
\end{bmatrix}
+
\begin{bmatrix}
0&1\\
0&1\\
0&1\\
\end{bmatrix}$

## 索引与切片

In [19]:
X,X[-1],X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [20]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [21]:
# 多个元素赋值
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 节省内存

In [22]:
# python先计算X+Y，再分配新的内存，并使Y指向该地址
before = id(Y)
Y = Y + X
id(Y) == before
# 坏处：不必要的内存开销；其他引用可能仍指向旧内存地址

False

In [ ]:
# 原地操作
## 提前分配
Z = torch.zeros_like(Y)
print("id(Z) before:", id(Z))
Z[:] = X + Y
print("id(Z) after:", id(Z))

## 若后续不再使用X，可以直接将结果存放在X中
before = id(X)
X += Y
id(X) == before

id(Z) before: 4857297680
id(Z) after: 4857297680
<class 'torch.Tensor'>


## 转换为其他python对象

In [ ]:
# torch tensor <-> numpy tensor，torch tensor 和 numpy array共享底层内存
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
# 将size为1的tensor转换为python标量
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 练习

In [27]:
# M<N?   M>N?
M=torch.arange(12,dtype=torch.float32).reshape((3,4))
N=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
M,N,M>N, M<N

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [28]:
# 三维tensor广播操作
U=torch.ones((2,3,1))
V=torch.ones((1,3,4))
U+V

tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])