# 数据操作

## 基础

- 张量(tensor)：n维数组，一个轴的tensor -> vector，两个轴的tensor -> matrix

In [1]:
import torch

/home/user23211/miniconda3/envs/d2l/lib/python3.13/site-packages/torch/_subclasses/functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# arange(start,end,step,...)
x=torch.arange(12)
x

In [4]:
x.shape

torch.Size([12])

In [5]:
# numbers of element
x.numel()

12

In [13]:
# reshape tensor
X=x.reshape(3,4)
# Automatically calculate the size of dimension
Y=x.reshape(-1,4)
X,Y

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [19]:
# all zero tensor
A=torch.zeros((2,3,4))
# all one tensor
B=torch.ones((2,3,4))
A,B

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

In [21]:
# 均值为0，标准差为1的标准高斯分布
torch.randn(3,4)

tensor([[ 1.2419, -0.9332,  0.4411,  1.0881],
        [ 0.9550, -0.2773,  2.0348, -0.7504],
        [ 1.9286,  1.8408, -0.5382, -0.6176]])

In [25]:
torch.tensor([[2,1],[3,1],[4,3]])

tensor([[2, 1],
        [3, 1],
        [4, 3]])

## 运算符

In [ ]:
# 加 减 乘 除
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y # ** 求幂操作：按位求幂

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [28]:
torch.exp(x) # e的幂

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [ ]:
# 连接 concatenate
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
# 0: y-coordinate  1: x-coordinate
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [31]:
# 按位比较
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [32]:
# 所有元素求和，产生一个单元素tensor
X.sum()

tensor(66.)

## 广播机制 broadcasting mechanism