# 数据预处理
## 读取数据集

In [1]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [2]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


## 处理缺失值

In [ ]:
# 插值法
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs["NumRooms"] = inputs["NumRooms"].fillna(inputs["NumRooms"].mean())
print(inputs)

# 删除法
# just remove the whole row

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [7]:
# 离散变量 -> 数值型的哑变量(dummy variable)
inputs=pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


## 转换成tensor

In [ ]:
import torch
X=torch.tensor(inputs.to_numpy(dtype=float))
Y=torch.tensor(outputs.to_numpy(dtype=float))
X,Y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

## 练习

In [21]:
# 创建更多行和列的数据集
# ../data/house_data_with_missing.csv

# 删除缺失值最多的列
## 读取数据集
data_practice=pd.read_csv("../data/house_data_with_missing.csv")
## 删除NaN最多的列
NAN_counts=data_practice.isna().sum()
max_NAN_column=NAN_counts.idxmax()
data_practice.drop(columns=[max_NAN_column],inplace=True)
## 填充数值型column的缺失值
numeric_columns=data_practice.select_dtypes(include=['number']).columns
data_practice[numeric_columns]=data_practice[numeric_columns].fillna(data_practice[numeric_columns].mean())
## 离散变量 -> 数值型的哑变量(dummy variable)
data_practice=pd.get_dummies(data_practice,dummy_na=True)
# 将预处理后的数据集转换为tensor
T=torch.tensor(data_practice.to_numpy(dtype=np.float32))
T

tensor([[3.0000e+00, 1.2743e+02, 1.9520e+03,  ..., 1.0000e+00, 0.0000e+00,
         0.0000e+00],
        [3.5711e+00, 7.1000e+01, 2.0070e+03,  ..., 0.0000e+00, 1.0000e+00,
         0.0000e+00],
        [5.0000e+00, 1.2100e+02, 2.0040e+03,  ..., 0.0000e+00, 0.0000e+00,
         1.0000e+00],
        ...,
        [2.0000e+00, 1.3000e+02, 1.9570e+03,  ..., 0.0000e+00, 1.0000e+00,
         0.0000e+00],
        [3.5711e+00, 6.3000e+01, 1.9930e+03,  ..., 1.0000e+00, 0.0000e+00,
         0.0000e+00],
        [3.0000e+00, 7.3000e+01, 1.9820e+03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]])